# This is for overriding the values in the values.yaml file if required
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mccp.fullname" . }}-cluster-service
  namespace: {{ .Release.Namespace }}
data:
  {{- if not .Values.config.checkpoint.enabled }}
  CHECKPOINT_DISABLE: 1
  {{- end }}
  {{- if and .Values.tls.enabled .Values.tls.secretName }}
  TLS_CERT_FILE: /etc/clusters-service-tls/tls.crt
  TLS_PRIVATE_KEY: /etc/clusters-service-tls/tls.key
  {{- end }}
