apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: gitopsset-podinfo
  namespace: default
spec:
  generators:
    - list:
        elements:
          - region: eu
          - region: us
  templates:
    - content:
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: podinfo-{{ .element.region }}
          namespace: default
        spec:
          interval: 5m
          chart:
            spec:
              chart: podinfo
              sourceRef:
                kind: HelmRepository
                name: podinfo
                namespace: default
              interval: 1m
          valuesFrom:
            - kind: ConfigMap
              name: "podinfo-{{ .element.region }}-config"
              optional: true
              valuesKey: values.yaml
---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: gitopsset-podinfo-config
  namespace: default
spec:
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: regions/eu/podinfo/config.yaml
          # name: eu
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: regions/us/podinfo/config.yaml
          # name: us
  templates:
    - content:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: podinfo-{{ .element.region }}-config
          namespace: default
        data:
          values.yaml: |
            ui:
              color: "{{ .element.values.ui.color }}"
