apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: gitopsset-podinfo
  namespace: default
spec:
  generators:
    - matrix:
        generators:
          - gitRepository:
              repositoryRef: foot-wge-dev-eu
              files:
                - path: podinfo/config.yaml
          - list:
              elements:
                - region: eu
    - matrix:
        generators:
          - gitRepository:
              repositoryRef: foot-wge-dev-us
              files:
                - path: podinfo/config.yaml
          - list:
              elements:
                - region: us
  templates:
    - content:
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: podinfo-{{ .element.region }}
          namespace: default
        spec:
          releaseName: podinfo
          interval: 5m
          kubeConfig:
            secretRef:
              name: "{{ .element.region }}-vcluster-kubeconfig"
          chart:
            spec:
              chart: podinfo
              sourceRef:
                kind: HelmRepository
                name: podinfo
                namespace: default
              interval: 1m
          values: |
            {{ .element.values | toJson }}
