---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-eu-env-values
  namespace: default
data:
  values.yaml: |
    ui:
      color: "#00ccff"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: gitopsset-configmaps
  namespace: default
spec:
  generators:
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: regions/eu/podinfo/config.yaml
    - gitRepository:
        repositoryRef: flux-system
        files:
          - path: regions/us/podinfo/config.yaml
  templates:
    - content:
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: podinfo-{{ .element.region }}
          namespace: default
        spec:
          interval: 5m
          chart:
            spec:
              chart: podinfo
              sourceRef:
                kind: HelmRepository
                name: podinfo
                namespace: default
              interval: 1m
          values:
            ui:
              color: "{{ .element.values.ui.color }}"
          valuesFrom:
            - kind: ConfigMap
              name: "podinfo-{{ .element.region }}-env-values"
              optional: true
              valuesKey: values.yaml
