policy-agent:
  enabled: true
  # maybe we disable the policy-agent with tilt so ignore timeouts etc
  failurePolicy: Ignore
  config:
    accountId: "weaveworks"
    clusterId: "tilt-cluster"

config:
  logLevel: debug
  auth:
    userAccount:
      enabled: false
    tokenPassthrough:
      enabled: true
  oidc:
    enabled: true
    issuerURL: "https://dev-46517780.okta.com/oauth2/default"
    redirectURL: "http://localhost:9001/oauth2/callback"
    cookieDuration: 1h
    claimUsername: "email"
    clientCredentialsSecret: "oidc-auth"

tls:
  enabled: false

# Turns on pipelines features when using Tilt.
enablePipelines: true

# Turns on terraform UI features for local dev
enableTerraformUI: true

extraEnvVars:
  - name: WEAVE_GITOPS_FEATURE_COST_ESTIMATION
    value: ""
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "false"
  # Can bump this up to 4+ to get more verbose logging
  - name: KLOG_VERBOSITY
    value: "7"
  - name: WEAVE_GITOPS_FEATURE_USE_USER_CLIENT_FOR_NAMESPACES
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_OIDC_AUTH_PASSTHROUGH
    value: "true"

extraEnvVarsSecret: ""

# Turns on UI elements for GitOps Run
enableRunUI: true

gitopssets-controller:
  enabled: true

# Re-clarify capiEnabled
global:
  capiEnabled: true
