policy-agent:
  enabled: true
  # maybe we disable the policy-agent with tilt so ignore timeouts etc
  failurePolicy: Ignore
  config:
    accountId: "weaveworks"
    clusterId: "tilt-cluster"

config:
  logLevel: debug

tls:
  enabled: false

# Turns on pipelines features when using Tilt.
enablePipelines: true

# Turns on terraform UI features for local dev
enableTerraformUI: true

extraEnvVars:
  # Can bump this up to >= 6 to get more verbose logging
  - name: KLOG_VERBOSITY
    value: "0"
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "false"
  # token pass through flags
  - name: WEAVE_GITOPS_FEATURE_USE_USER_CLIENT_FOR_NAMESPACES
    value: "true"
  - name: WEAVE_GITOPS_FEATURE_OIDC_AUTH_PASSTHROUGH
    value: "true"
  # debug flag, set to true to disable helm cache, useful if it doesn't
  # have access to much due to token passthrough
  - name: DEBUG_DISABLE_HELM_REPO_WATCHER
    value: "false"
  # cost estimation feature
  - name: WEAVE_GITOPS_FEATURE_COST_ESTIMATION
    value: ""

extraEnvVarsSecret: ""

# Turns on UI elements for GitOps Run
enableRunUI: true

gitopssets-controller:
  enabled: true

# Re-clarify capiEnabled
global:
  capiEnabled: true
