policy-agent:
  enabled: true
  # maybe we disable the policy-agent with tilt so ignore timeouts etc
  failurePolicy: Ignore
  config:
    accountId: "weaveworks"
    clusterId: "management"

config:
  logLevel: debug
  oidc:
    enabled: true
    issuerURL: https://dex-01.wge.dev.weave.works
    clientCredentialsSecret: client-credentials
    redirectURL: http://localhost:30080/oauth2/callback

tls:
  enabled: false

# Turns on pipelines features when using Tilt.
enablePipelines: true

enableExplorer: true

# Turns on terraform UI features for local dev
enableTerraformUI: true

useQueryServiceBackend: false

service:
  type: NodePort
  ports:
    https: 8000
  nodePorts:
    https: 30080
extraEnvVars:
  - name: WEAVE_GITOPS_FEATURE_COST_ESTIMATION
    value: ""
  - name: WEAVE_GITOPS_FEATURE_TELEMETRY
    value: "false"
  - name: BITBUCKET_SERVER_HOSTNAME
    value: "bitbucket.yiannis.net"
  # - name: DEV_MODE
  #   value: "true"
  - name: WEAVE_GITOPS_ENABLE_PROFILING
    value: "true"

extraEnvVarsSecret: ""

# Turns on UI elements for GitOps Run
enableRunUI: true

gitopssets-controller:
  enabled: true

# Re-clarify capiEnabled
global:
  capiEnabled: true

metrics:
  # Enables metrics generation and prometheus endpoint
  enabled: true
  service:
    annotations:
      prometheus.io/scrape: "true"
