on:
  push:
    branches-ignore:
      - "main"
    tags-ignore:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: run tests
jobs:
  ui-cypress:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.BUILD_BOT_PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run selector tests
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: ui-cra
          component: true
