{{- if .Values.collector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mccp
    app.kubernetes.io/component: collector
  name: {{ include "mccp.fullname" . }}-collector
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mccp
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mccp
        app.kubernetes.io/component: collector
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: {{ include "mccp.fullname" . }}-collector
        image: {{ .Values.images.collector }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: collector
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 8081
            name: health
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      serviceAccountName: collector
      terminationGracePeriodSeconds: 10
{{- end }}
